// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IERC721Mintable$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IERC721Mintable";
  readonly sourceName: "contracts/interfaces/IERC721Mintable.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"user","type":"address"}],"name":"getUserHighestTier","outputs":[{"internalType":"uint8","name":"","type":"uint8"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"user","type":"address"},{"internalType":"uint8","name":"tier","type":"uint8"}],"name":"hasTierNFT","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"tokenId","type":"uint256"},{"internalType":"uint8","name":"tier","type":"uint8"}],"name":"mintReward","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IERC721Mintable.sol";
  readonly buildInfoId: "solc-0_8_28-099f8be52d60a1b15c575376175107d53525e129";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IERC721Mintable"]: IERC721Mintable$Type;
    ["contracts/interfaces/IERC721Mintable.sol:IERC721Mintable"]: IERC721Mintable$Type;
  }
}