/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IERC721MintableInterface extends Interface {
    getFunction(nameOrSignature: "getUserHighestTier" | "hasTierNFT" | "mintReward"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getUserHighestTier', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'hasTierNFT', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'mintReward', values: [AddressLike, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'getUserHighestTier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasTierNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintReward', data: BytesLike): Result;
  }

  

  export interface IERC721Mintable extends BaseContract {
    
    connect(runner?: ContractRunner | null): IERC721Mintable;
    waitForDeployment(): Promise<this>;

    interface: IERC721MintableInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getUserHighestTier: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    hasTierNFT: TypedContractMethod<
      [user: AddressLike, tier: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    mintReward: TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, tier: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getUserHighestTier'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'hasTierNFT'): TypedContractMethod<
      [user: AddressLike, tier: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'mintReward'): TypedContractMethod<
      [to: AddressLike, tokenId: BigNumberish, tier: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }