#!/bin/bash

# MeeChain Token Deployment Script
# This script helps deploy MeeChainToken.sol to BNB Smart Chain

echo "🚀 MeeChain Token Deployment Guide"
echo "=================================="
echo ""
echo "⚠️  Prerequisites:"
echo "   1. MetaMask wallet with BNB for gas fees"
echo "   2. Private key ready (keep it secret!)"
echo "   3. Node.js >= 16 installed"
echo ""
echo "📋 Deployment Options:"
echo ""
echo "Option 1: Deploy with Remix IDE (Recommended for beginners)"
echo "-----------------------------------------------------------"
echo "1. Go to https://remix.ethereum.org/"
echo "2. Create new file: MeeChainToken.sol"
echo "3. Copy contract code from: contracts/MeeChainToken.sol"
echo "4. Compile with Solidity 0.8.20"
echo "5. Connect MetaMask to BSC Testnet or Mainnet"
echo "6. Deploy contract"
echo "7. Save contract address"
echo "8. Update viewer/config/contracts.ts with new address"
echo ""
echo "Option 2: Deploy with Hardhat"
echo "------------------------------"
echo "1. Install Hardhat: npm install --save-dev hardhat"
echo "2. Install OpenZeppelin: npm install @openzeppelin/contracts"
echo "3. Create hardhat.config.js with BSC network config"
echo "4. Create deploy script in scripts/deployMEE.js"
echo "5. Run: npx hardhat run scripts/deployMEE.js --network bscTestnet"
echo "6. Save contract address"
echo "7. Update viewer/config/contracts.ts with new address"
echo ""
echo "🔧 After Deployment:"
echo "-------------------"
echo "1. Verify contract on BscScan"
echo "2. Update MEE_ADDRESS in viewer/config/contracts.ts"
echo "3. Update MEE_ADDRESS in viewer/src/config/contracts.ts"
echo "4. Test swap functionality on testnet first"
echo "5. Deploy to mainnet when ready"
echo ""
echo "📚 For detailed instructions, see: MEECHAIN_TOKEN_GUIDE.md"
echo ""
